package com.batch.android.json

import org.junit.Assert.*
import org.junit.Test

/** Test class for [JSONUtils] Full test case generated by Gemini */
class JSONUtilsTest {

    @Test
    fun testJsonObjectContainsValuesFrom_nullExpected_nullActual() {
        assertTrue(JSONUtils.jsonObjectContainsValuesFrom(null, null))
    }

    @Test
    fun testJsonObjectContainsValuesFrom_nullExpected_notNullActual() {
        assertFalse(JSONUtils.jsonObjectContainsValuesFrom(null, JSONObject()))
    }

    @Test
    fun testJsonObjectContainsValuesFrom_notNullExpected_nullActual() {
        assertFalse(JSONUtils.jsonObjectContainsValuesFrom(JSONObject(), null))
    }

    @Test
    fun testJsonObjectContainsValuesFrom_emptyObjects() {
        assertTrue(JSONUtils.jsonObjectContainsValuesFrom(JSONObject(), JSONObject()))
    }

    @Test
    fun testJsonObjectContainsValuesFrom_expectedHasMoreKeys() {
        val expected =
            JSONObject().apply {
                put("key1", "value1")
                put("key2", "value2")
            }
        val actual = JSONObject().apply { put("key1", "value1") }
        assertFalse(JSONUtils.jsonObjectContainsValuesFrom(expected, actual))
    }

    @Test
    fun testJsonObjectContainsValuesFrom_actualHasMoreKeys() {
        val expected = JSONObject().apply { put("key1", "value1") }
        val actual =
            JSONObject().apply {
                put("key1", "value1")
                put("key2", "value2")
            }
        assertTrue(JSONUtils.jsonObjectContainsValuesFrom(expected, actual))
    }

    @Test
    fun testJsonObjectContainsValuesFrom_sameKeyDifferentValue() {
        val expected = JSONObject().apply { put("key1", "value1") }
        val actual = JSONObject().apply { put("key1", "otherValue") }
        assertFalse(JSONUtils.jsonObjectContainsValuesFrom(expected, actual))
    }

    @Test
    fun testJsonObjectContainsValuesFrom_matchingSimpleValues() {
        val expected =
            JSONObject().apply {
                put("string", "test")
                put("int", 123)
                put("boolean", true)
            }
        val actual =
            JSONObject().apply {
                put("string", "test")
                put("int", 123)
                put("boolean", true)
                put("extraKey", "extraValue")
            }
        assertTrue(JSONUtils.jsonObjectContainsValuesFrom(expected, actual))
    }

    @Test
    fun testJsonObjectContainsValuesFrom_nestedJsonObjectMatch() {
        val expected =
            JSONObject().apply {
                put("nested", JSONObject().apply { put("innerKey", "innerValue") })
            }
        val actual =
            JSONObject().apply {
                put("nested", JSONObject().apply { put("innerKey", "innerValue") })
                put("otherKey", "value")
            }
        assertTrue(JSONUtils.jsonObjectContainsValuesFrom(expected, actual))
    }

    @Test
    fun testJsonObjectContainsValuesFrom_nestedJsonObjectMismatch() {
        val expected =
            JSONObject().apply {
                put("nested", JSONObject().apply { put("innerKey", "innerValue") })
            }
        val actual =
            JSONObject().apply {
                put("nested", JSONObject().apply { put("innerKey", "differentInnerValue") })
            }
        assertFalse(JSONUtils.jsonObjectContainsValuesFrom(expected, actual))
    }

    @Test
    fun testJsonObjectContainsValuesFrom_nestedJsonArrayMatch() {
        val expected =
            JSONObject().apply {
                put(
                    "array",
                    JSONArray().apply {
                        put("item1")
                        put(JSONObject().apply { put("nestedInArray", "value") })
                    },
                )
            }
        val actual =
            JSONObject().apply {
                put(
                    "array",
                    JSONArray().apply {
                        put("item1")
                        put(JSONObject().apply { put("nestedInArray", "value") })
                        put("extraItemInArray")
                    },
                )
                put("otherKey", "value")
            }
        assertTrue(JSONUtils.jsonObjectContainsValuesFrom(expected, actual))
    }

    @Test
    fun testJsonObjectContainsValuesFrom_nestedJsonArrayMismatch_value() {
        val expected = JSONObject().apply { put("array", JSONArray().apply { put("item1") }) }
        val actual =
            JSONObject().apply {
                put(
                    "array",
                    JSONArray().apply {
                        put("item2") // different value
                    },
                )
            }
        assertFalse(JSONUtils.jsonObjectContainsValuesFrom(expected, actual))
    }

    @Test
    fun testJsonObjectContainsValuesFrom_nestedJsonArrayMismatch_orderNotGuaranteedButContentMatters() {
        val expected =
            JSONObject().apply {
                put(
                    "array",
                    JSONArray().apply {
                        put("item1")
                        put("item2")
                    },
                )
            }
        // Even if actual has the items in a different order, it should still fail
        // because jsonArrayContainsValuesFrom checks for subsets in order.
        val actual =
            JSONObject().apply {
                put(
                    "array",
                    JSONArray().apply {
                        put("item2")
                        put("item1")
                    },
                )
            }
        assertTrue(JSONUtils.jsonObjectContainsValuesFrom(expected, actual))
    }

    @Test
    fun testJsonObjectContainsValuesFrom_keyMissingInActual() {
        val expected =
            JSONObject().apply {
                put("key1", "value1")
                put("missingKey", "value2")
            }
        val actual = JSONObject().apply { put("key1", "value1") }
        assertFalse(JSONUtils.jsonObjectContainsValuesFrom(expected, actual))
    }

    @Test
    fun testJsonObjectContainsValuesFrom_differentTypesForKey() {
        val expected = JSONObject().apply { put("key", JSONObject()) }
        val actual = JSONObject().apply { put("key", "not_an_object") }
        assertFalse(JSONUtils.jsonObjectContainsValuesFrom(expected, actual))
    }

    // --- Tests for jsonArrayContainsValuesFrom ---

    @Test
    fun testJsonArrayContainsValuesFrom_nullExpected_nullActual() {
        assertTrue(JSONUtils.jsonArrayContainsValuesFrom(null, null))
    }

    @Test
    fun testJsonArrayContainsValuesFrom_nullExpected_notNullActual() {
        assertFalse(JSONUtils.jsonArrayContainsValuesFrom(null, JSONArray()))
    }

    @Test
    fun testJsonArrayContainsValuesFrom_notNullExpected_nullActual() {
        assertFalse(JSONUtils.jsonArrayContainsValuesFrom(JSONArray(), null))
    }

    @Test
    fun testJsonArrayContainsValuesFrom_emptyArrays() {
        assertTrue(JSONUtils.jsonArrayContainsValuesFrom(JSONArray(), JSONArray()))
    }

    @Test
    fun testJsonArrayContainsValuesFrom_expectedLongerThanActual() {
        val expected =
            JSONArray().apply {
                put("item1")
                put("item2")
            }
        val actual = JSONArray().apply { put("item1") }
        assertFalse(JSONUtils.jsonArrayContainsValuesFrom(expected, actual))
    }

    @Test
    fun testJsonArrayContainsValuesFrom_actualLongerThanExpected_subset() {
        val expected = JSONArray().apply { put("item1") }
        val actual =
            JSONArray().apply {
                put("item1")
                put("item2")
            }
        assertTrue(JSONUtils.jsonArrayContainsValuesFrom(expected, actual))
    }

    @Test
    fun testJsonArrayContainsValuesFrom_exactMatchSimpleValues() {
        val expected =
            JSONArray().apply {
                put("a")
                put(1)
                put(true)
            }
        val actual =
            JSONArray().apply {
                put("a")
                put(1)
                put(true)
            }
        assertTrue(JSONUtils.jsonArrayContainsValuesFrom(expected, actual))
    }

    @Test
    fun testJsonArrayContainsValuesFrom_subsetWithSimpleValues() {
        val expected =
            JSONArray().apply {
                put("a")
                put(1)
            }
        val actual =
            JSONArray().apply {
                put("a")
                put(1)
                put(true)
                put("extra")
            }
        assertTrue(JSONUtils.jsonArrayContainsValuesFrom(expected, actual))
        assertFalse(JSONUtils.jsonArrayContainsValuesFrom(actual, expected))
    }
}
